### ISSUE TITLE
Error: too big array size

### ISSUE THREAD

**Issue by HironTez** [LinusU/decode-ico#8]
Hi, thanks for the tool. I'm having trouble decoding Google Chrome's ico buffer. The size of the array is larger than node.js can handle. This is the error message:
```
RangeError: Invalid typed array length: 1353219496
    at new Uint8Array (<anonymous>)
    at ...\node_modules\decode-ico\index.js:87:18
    at Function.from (<anonymous>)
    at decodeIco (...\node_modules\decode-ico\index.js:64:16)
```

**Comment by LinusU** [comment]
Can you share a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by HironTez** [comment]
@LinusU Sure. As i mentioned it's just the Google Chrome icon.
That's the snippet that results the error:

```ts
import { extractIcon } from "@inithink/exe-icon-extractor";
import icoToPng from "ico-to-png";

const icon = extractIcon("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe", "large");
icoToPng(icon, 256).then((png) => console.log(png));
```

It works fine with other apps
